import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";

import ModelPredictionCount from "./components/predictionCountCard";
import ModelReportCard from "./components/modelReportCard";

const inter = Inter({
  subsets: ["latin"],
});



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>

        <Navbar />

        <main className="container mx-auto px-4 md:pz-8 py-4">

          <section className="flex flex-col md:flex-row md:space-x-6 justify-center items-start">
            {children}
          </section>
        </main>

      </body>
    </html>
  );
}
