import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Matches from "./components/Match";

const inter = Inter({
  subsets: ["latin"],
});



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className=" md:py-2 text-textPrimary">
          <Navbar />
          <section className="flex space-x-4 justify-center">

            {children}
          </section>
        </main>

      </body>
    </html>
  );
}
